name: Code Formatting Check

on:
  pull_request:
    paths:
      - ".github/workflows/code-formatting-check.yml"
      - "GCA51/**"
  push:
    paths:
      - ".github/workflows/code-formatting-check.yml"
      - "GCA51/**"

jobs:
  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: arduino/arduino-lint-action@v2
        with:
          path: GCA51/
          project-type: sketch
          library-manager: false

  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "GCA51/**/*.ino,GCA51/**/*.h,GCA51/**/*.cpp"

      - name: Formatting feedback
        run: |
          if ! git diff --color --exit-code; then
            echo "Please do an Auto Format on the sketches:"
            echo "Arduino IDE: Tools > Auto Format"
            echo "Arduino Web Editor: Ctrl + B"
            exit 1
          fi
